// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyysa3dWTK3QkLKr-OwNX16aipKHTDX4Y',
    appId: '1:540733910678:web:fd5b46a7a013c3d2419cb7',
    messagingSenderId: '540733910678',
    projectId: 'foodninja-project',
    authDomain: 'foodninja-project.firebaseapp.com',
    storageBucket: 'foodninja-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiSSGDs-eSb9cuVMXN7IX8rhXre1ygoc',
    appId: '1:540733910678:android:05dbcec25da5f3c6419cb7',
    messagingSenderId: '540733910678',
    projectId: 'foodninja-project',
    storageBucket: 'foodninja-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqcdhKolxI_e6KhikJ39q5a8n_o1Rj9bA',
    appId: '1:540733910678:ios:11730e9a37081219419cb7',
    messagingSenderId: '540733910678',
    projectId: 'foodninja-project',
    storageBucket: 'foodninja-project.appspot.com',
    iosBundleId: 'com.example.foodninja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqcdhKolxI_e6KhikJ39q5a8n_o1Rj9bA',
    appId: '1:540733910678:ios:a8d769e3d7b358f7419cb7',
    messagingSenderId: '540733910678',
    projectId: 'foodninja-project',
    storageBucket: 'foodninja-project.appspot.com',
    iosBundleId: 'com.example.foodninja.RunnerTests',
  );
}
